### ISSUE TITLE
Throttle always zero in energywidget

### ISSUE THREAD

**Issue by philipoe** [ethz-asl/qgc_asl#12]
Throttle always shows 0% in energywidget. This is dangerous because it does not allow an easy identification ob motor failures. This was observed e.g. during AS-3 26-hour flight. @oberion Can you quickly verify using the mavlink-flight-logs in the respective folder on the group server?

**Comment by mhugentobler** [comment]
just saw that this is still the case in the updated version of the widget, but it doesnt look like a qgc problem. since qgc gets VFR_HUD.throttle = 0 at all times, this is displayed correctly.
the error must be on the pixhawk side

**Comment by philipoe** [comment]
Yes, see https://github.com/ethz-asl/fw_px4/blob/master/src/modules/mavlink/mavlink_messages.cpp#L940. Mavlink subscribes to actuator control group 0, see https://github.com/ethz-asl/fw_px4/blob/master/src/modules/mavlink/mavlink_messages.cpp#L912 , while aslctrl publishes on control group 1, see https://github.com/ethz-asl/fw_px4/blob/master/src/modules/aslctrl/helpers/subs.cpp#L433 . This is by design, was implemented by Bartosz.

Easiest fix for now: @mhugentobler Can you just update the topic that is subscribed to at https://github.com/ethz-asl/fw_px4/blob/master/src/modules/mavlink/mavlink_messages.cpp#L912 to the actuator control group 1? You can assign me in your PR in the fw_px4 repo.

**Comment by philipoe** [comment]
Fixed by https://github.com/ethz-asl/fw_px4/pull/103 , closing.
