### ISSUE TITLE
Show parameter descriptions in side bar

### ISSUE THREAD

**Issue by tstastny** [ethz-asl/qgc_asl#25]
Appears there is some space meant for parameter descriptions in the side bar that is opened whenever modifying parameters in QGC v3. Would be great to show text there from the param comments in the param.c files on pixhawk.

**Comment by philipoe** [comment]
Sounds like this fits SOLAR³ perfectly. Why is it not showing at the moment? Should it be implemented on QGC & Pixhawk side already?

**Comment by tstastny** [comment]
Looks as thought it could be planned already - I will check through upstream commits today to see if it was discussed anywhere - otherwise, maybe we are able to easily put it ourselves.

**Comment by philipoe** [comment]
This is already implemented in the current QGC v3.3. Note that for new parameters (e.g. ASL Custom parameters) to appear there, the corresponding PX4 firmware needs to be flashed once via QGC (!) and a USB cable. Closing this issue.
