### ISSUE TITLE
LED-plugin causes Windows build to fail

### ISSUE THREAD

**Issue by philipoe** [ethz-asl/qgc_asl#37]
@asm3 While compiling the current master on Windows 10 with QtCreator 4.2 (_edit: This is included in QT v5.7.1_) and the MSVC2015 compiler (as suggested in the qgc documentation) I get the following errors in the LED-class/files:

> ..\qgc_v3\src\ui\LED.cc(11): warning C4273: 'LED::LED': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(21): note: see previous definition of '{ctor}'
..\qgc_v3\src\ui\LED.cc(29): warning C4273: 'LED::~LED': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(22): note: see previous definition of '{dtor}'
..\qgc_v3\src\ui\LED.cc(35): warning C4273: 'LED::diameter': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(24): note: see previous definition of 'diameter'
..\qgc_v3\src\ui\LED.cc(41): warning C4273: 'LED::setDiameter': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(25): note: see previous definition of 'setDiameter'
..\qgc_v3\src\ui\LED.cc(56): warning C4273: 'LED::color': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(27): note: see previous definition of 'color'
..\qgc_v3\src\ui\LED.cc(62): warning C4273: 'LED::setColor': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(28): note: see previous definition of 'setColor'
..\qgc_v3\src\ui\LED.cc(69): warning C4273: 'LED::alignment': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(30): note: see previous definition of 'alignment'
..\qgc_v3\src\ui\LED.cc(75): warning C4273: 'LED::setAlignment': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(31): note: see previous definition of 'setAlignment'
..\qgc_v3\src\ui\LED.cc(83): warning C4273: 'LED::setFlashRate': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(43): note: see previous definition of 'setFlashRate'
..\qgc_v3\src\ui\LED.cc(91): warning C4273: 'LED::setFlashing': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(42): note: see previous definition of 'setFlashing'
..\qgc_v3\src\ui\LED.cc(99): warning C4273: 'LED::startFlashing': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(44): note: see previous definition of 'startFlashing'
..\qgc_v3\src\ui\LED.cc(105): warning C4273: 'LED::stopFlashing': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(45): note: see previous definition of 'stopFlashing'
..\qgc_v3\src\ui\LED.cc(112): warning C4273: 'LED::setState': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(40): note: see previous definition of 'setState'
..\qgc_v3\src\ui\LED.cc(119): warning C4273: 'LED::toggleState': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(41): note: see previous definition of 'toggleState'
..\qgc_v3\src\ui\LED.cc(126): warning C4273: 'LED::heightForWidth': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(48): note: see previous definition of 'heightForWidth'
..\qgc_v3\src\ui\LED.cc(132): warning C4273: 'LED::sizeHint': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(49): note: see previous definition of 'sizeHint'
..\qgc_v3\src\ui\LED.cc(138): warning C4273: 'LED::minimumSizeHint': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(50): note: see previous definition of 'minimumSizeHint'
..\qgc_v3\src\ui\LED.cc(144): warning C4273: 'LED::paintEvent': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(53): note: see previous definition of 'paintEvent'
..\qgc_v3\src\ui\LED.cc(193): warning C4273: 'LED::state': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(33): note: see previous definition of 'state'
..\qgc_v3\src\ui\LED.cc(199): warning C4273: 'LED::isFlashing': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(35): note: see previous definition of 'isFlashing'
..\qgc_v3\src\ui\LED.cc(205): warning C4273: 'LED::flashRate': inconsistent dll linkage
c:\src\fw_qgc\qgc_v3\src\ui\LED.h(37): note: see previous definition of 'flashRate'

... and later the compile then fails with:

> moc\moc_LED.cpp(145): error C2491: 'LED::staticMetaObject': definition of dllimport static data member not allowed
moc\moc_LED.cpp(152): warning C4273: 'LED::metaObject': inconsistent dll linkage
c:\src\fw_qgc\build-qgroundcontrol-desktop_qt_5_7_1_msvc2015_32bit-release\moc\../../qgc_v3/src/ui/LED.h(11): note: see previous definition of 'metaObject'
moc\moc_LED.cpp(157): warning C4273: 'LED::qt_metacast': inconsistent dll linkage
c:\src\fw_qgc\build-qgroundcontrol-desktop_qt_5_7_1_msvc2015_32bit-release\moc\../../qgc_v3/src/ui/LED.h(11): note: see previous definition of 'qt_metacast'
moc\moc_LED.cpp(165): warning C4273: 'LED::qt_metacall': inconsistent dll linkage
c:\src\fw_qgc\build-qgroundcontrol-desktop_qt_5_7_1_msvc2015_32bit-release\moc\../../qgc_v3/src/ui/LED.h(11): note: see previous definition of 'qt_metacall'
jom: C:\src\fw_qgc\build-qgroundcontrol-Desktop_Qt_5_7_1_MSVC2015_32bit-Release\Makefile.Release [obj\moc_LED.obj] Error 2

I don't know how this class was implemented. Did you use QtDesigner? Any idea on why this is happening (or what DLL are you potentially including there that might cause this)?

**Comment by tstastny** [comment]
is this for v2.3, or v3? -- because QGC documentation for v3 master (what our working version is based on -- minus some latest commits) says "Qt version: 5.7.1 ONLY". I think I'm actually using 5.5.1. And things still compile (on ubuntu at least). But I guess 4.x is quite old. :/

**Comment by ASM3** [comment]
As TJ has already mentioned, I based it on QT ver 5.7.1 (QT creator, Ubuntu build using GCC x86 64bit)

**Comment by philipoe** [comment]
QGCv3, as we dont have the LEDs in v2.3. I am using Qt v5.7.1 (but this includes QtCreator v. 4.2).

**Comment by mhugentobler** [comment]
i use qtcreater 3.5.1 and qt 5.5.1 on ubuntu. i think i would uninstall windows and boot up ubuntu for a quick fix :)

**Comment by ASM3** [comment]
![images](https://user-images.githubusercontent.com/3127009/27659427-b2dab484-5c53-11e7-9b69-963280cf8867.jpg)

(I will check it out tomorrow on your machine)

**Comment by ASM3** [comment]
Which Visual Studio version is installed on your machine?

**Comment by philipoe** [comment]
MSVC2015 enterprise with Update Pack 3, English, from dreamspark/IDES (i.e. basically what is suggested in the QGC documentation). Just in case you plan on installing this: Let me know if there is issues (i had quite some and lost a couple of hours on this today...).

**Comment by mantelt** [comment]
I also quickly tried to compile it under windows 7 yesterday. The problem for sure is @ASM3 s "stolen" LED stuff. I was also using MSVC2015 with QT 5.7.1 and the newest qtcreator (4.3?). 

And yes, it works flawlessly with linux, but some stuff only runs on windows. so would be nice to have QGC also run on windows

**Comment by ASM3** [comment]
Yes, it needs to be verified under MS windows (probably there is a missing dll or one of the MSwin definition is missing).
As discussed before, it would be very beneficial to standardise our environment (as we don't have enough resources for computability tests)  

BTW, why stolen? it is an official ICS OS plug-in

**Comment by mantelt** [comment]
possibly solved with #39. Rather small change needed

**Comment by philipoe** [comment]
Fixed by #42 .
