### ISSUE TITLE
Loiter WPs loaded from file ALWAYS as relative to home

### ISSUE THREAD

**Issue by tstastny** [ethz-asl/qgc_asl#41]
It seems regardless of how loiter points are saved in a mission file, when loaded from file, they appear in QGC with the 'relative to home' checkbox checked.

**Comment by tstastny** [comment]
also the visual display of the altitude on bottom bar doesnt change when checking or unchecking altitude relative unless you change the numeric value of the altitude. Lorenz Meier also noticed this -- there is already a fix upstream (https://github.com/mavlink/qgroundcontrol/pull/5343). However, does not fix upload problem (just tested with cherry-pick).

**Comment by philipoe** [comment]
@tstastny Is this issue still needed? If not please close it.

**Comment by tstastny** [comment]
not sure. need to check with latest QGC

**Comment by philipoe** [comment]
Checked? If solved please close, otherwise transfer this issue to the QGC main repo.
