### ISSUE TITLE
Energy widget flickers (values and display) 

### ISSUE THREAD

**Issue by ASM3** [ethz-asl/qgc_asl#43]
the energy widget flickers when data is streamed.
It switches on and off between default and read values

**Comment by philipoe** [comment]
Fixed in c77ee17d766c82c2ad0d345960db5c7578092b9c . Will test more (and close this issue if OK) once you send me the telemetry log files @ASM3 .

**Comment by philipoe** [comment]
Fixed in https://github.com/ethz-asl/fw_qgc/commit/3a0cd71973506c3a1ffde95ff2559ab92e397a95, closing.
