### ISSUE TITLE
servo channel error mapping is wrong

### ISSUE THREAD

**Issue by ASM3** [ethz-asl/qgc_asl#45]
servo channel error mapping is wrong:
ch 7 shows: Servo 17 faulty
ch 6 shows: Servo 16 faulty
....
ch 1 shows: Servo 0  faulty

**Comment by philipoe** [comment]
Good, will fix. Hint: If you always provide me with log files for bugs that were found, then i can actually test the stuff that i am changing ;) You can even attach the logs to a github issue, it is really neat. Do you still have these logs?

**Comment by ASM3** [comment]
works fine (tested)
