### ISSUE TITLE
Automatically display new waypoints in "plan" window when set from mavros

### ISSUE THREAD

**Issue by tstastny** [ethz-asl/qgc_asl#5]
Waypoints can be refreshed and seen as "onboard", but will not show up on the display. Should implement automatic polling and refreshing.

**Comment by oberion** [comment]
What do you mean by that, The waypoints should be already updated when you change them in QGC directly (of course) but they should also be updated on GGC when you change them over the sensorpod. I have implemented this already once. Is this not working anymore?

**Comment by tstastny** [comment]
You have sent new waypoints to px4 from the sensorpod?

What I am referring to is specifically sending waypoints via mavros to the px4, and then simultaneously updating the display on QGC (which is getting forwarded msgs from the mavros instance, whether on sensorpod, or the ground station, doesnt really matter). This chain: QGC <-> MAVROS <-> PX4. This works.. but the only difference is that the waypoints don't actually get refershed graphically on the google/bing map. The are shown in the "onboard waypoints" widget, but no on the map.

**Comment by tstastny** [comment]
I found the bool to change to at least show the new onboard waypoints in the editable view whenever you hit refresh. (see bcc947b9e8a9d1f8b1892eca731bfcf6f77830bc) After thinking a little, I think it's probably not wise to go further and automatically pull at some rate the onboard waypoints. Because that's just going to annoy the hell out of you while trying to plan a new mission from QGC. Something better to implement would perhaps be a notification that let's you know on QGC when new onboard waypoints have been set (or notices some change in onboard waypoints that you didnt make or set from QGC). @oberion Any recommendations on how this may be done or look?

**Comment by tstastny** [comment]
Note to self (and anyone else who cares): This is likely a small change that needs to be made on MAVROS. Automatically pull onboard waypoints (at some rate) and SEND a message to QGC telling it the onboard points have been updated. Then on QGC side.. some kind of pop-up or flashing text that lets you know the onboard points have changed, and you need to refresh.

**Comment by mantelt** [comment]
@tstastny Is this still an issue? Somehow I feel like this is handled on the mavros side already. Maybe it needs to be configured properly, but I'm quite positive that I saw exactly this functionality (mavros sending waypoints to QGC) some time ago.

**Comment by tstastny** [comment]
Yes, the waypoint will get sent. And if you press "refresh" they are displayed. But there is no indication that the waypoint have changed unless you arbitrarily refresh occasionally (or you see the aircraft deviating from the shown path). Would be good to have some message flash in QGC whenever the mission has been changed due to MAVROS sending new waypoints. I can look into this.. but just havent had the time so far (/it hasnt been a top priority).

**Comment by tstastny** [comment]
Only wanted this for SHERPA. And now SHERPA is over. May still be interesting in the future to include this, if we e.g. send wp's from @philipoe's planning framework. But would need to be made an issue in v3.x, where the behavior is still unknown at the moment. Closing.
