### ISSUE TITLE
SensorPod Status plugin uses fixed component id

### ISSUE THREAD

**Issue by mantelt** [ethz-asl/qgc_asl#6]
When sending payload_control command, a fixed component id is used. (https://github.com/ethz-asl/fw_qgc/blob/master/src/ui/sensorpodstatus.cpp#L88)

probably may use uas->mavlink->getComponentId()

**Comment by mantelt** [comment]
haha, even easier to fix: #7

**Comment by philipoe** [comment]
Closing, fixed by a1cbd9b8d516cf9e221aa3a71ae73c63567066d3 .
