### ISSUE TITLE
Mission and/or Param request timeout

### ISSUE THREAD

**Issue by tstastny** [ethz-asl/qgc_asl#8]
Can sometimes happen that the mission and/or params are not found and displayed on qgc.

Error reproduction: I have only been able to reproduce this (mainly for the mission items) by deleting the dataman on the sd card.

Mean-time fix: to get around this, one must open qgc and boot the pixhawk. Once pixhawk is fully booted, cut power to pixhawk, then set a few waypoints on qgc and hit the "set" button (even though pixhawk is not connected). Reboot pixhawk, and re-"set" the waypoints. Should be working now.

NOTE: this mean-time fix is not a solution. Also, does not consider the params issue, which I have not reliably been able to reproduce, though I saw this in two separate flight test attempts in Tobelhof.

NOTE-2: the errors are only reliably reproducible with a GPS fix.

NOTE-3: have not successfully been able to reproduce the original error without manually deleting the dataman. But in general, deleting the dataman actually should not cause this error anyway.

**Comment by philipoe** [comment]
> Once pixhawk is fully booted, cut power to pixhawk, then set a few waypoints on qgc [...]

Note: Instead of fully cutting the power to Pixhawk (which is basically not possible on AtlantikSolar at least), it seems to also be enough to issue a `mavlink stop-all` command (which then completely stops the mavlink comms).

**Comment by philipoe** [comment]
Closing issue because this affects an overly old version of QGC.
